# Generated by Django 4.1.2 on 2022-12-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='student_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='student_phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
